[tox]
isolated_build = True
envlist = pylint,black,docformatter

[gh-actions]
python =
    3.13: pylint,black,docformatter

[testenv:pylint]
deps =
    pytest-pylint == 0.*
commands =
    pylint --output-format=colorized ai_jaedolph.py

[testenv:black]
skip_install = True
deps =
    black == 26.*
commands =
    black --check --diff --color ai_jaedolph.py

[testenv:docformatter]
skip_install = True
deps =
    docformatter == 1.7.*
commands =
    docformatter --check ai_jaedolph.py
